config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  mount GraphiQL::Rails::Engine, at: '/graphiql', graphql_path: '/graphql' if Rails.env.development?
  post '/graphql', to: 'graphql#execute'

  namespace :api do
    namespace :v1 do
      resources :users, only: [:index] do
        collection do
          get :count_posts
        end
      end
    end
  end

  root to: 'posts#index'

  devise_for :users, controllers: {
    sessions: 'sessions'
  }, path: '', path_names: { sign_in: 'sign_in', sign_out: 'sign_out' }

  resources :posts, only: %i[show new create edit update destroy] do
    collection do
      get :export_to_spreadsheet
    end
  end

  resources :chain_words, only: %i[index create]

  resources :user_manuals, only: [] do
    collection do
      get :test
    end
  end
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 255 }
  validates :content, presence: true, length: { maximum: 65_535 }
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]

  def index
    @posts = current_user.posts.order(id: :desc)
  end

  def show; end

  def new
    @post = current_user.posts.new
  end

  def edit; end

  def create
    @post = current_user.posts.new(post_params)

    if @post.save
      redirect_to root_path, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to root_path, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path, notice: 'Post was successfully destroyed.'
  end

  def export_to_spreadsheet
    spreadsheet_service = SpreadsheetService.new
    spreadsheet_service.create_spreadsheet(current_user) if current_user.spreadsheet_id.blank?
    spreadsheet_service.export_posts(current_user)
    redirect_to root_path, notice: 'Post was successfully exported to Spreadsheet.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end

  def set_post
    @post = current_user.posts.find(params[:id])
  end
end

app/views/posts/_form.html.slim
= form_with(model: post) do |form|
  - if post.errors.any?
    div style="color: red"
      h2 = "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - post.errors.full_messages.each do |message|
          li = message

  .field
    = form.label :title
    = form.text_field :title, required: true

  .field
    = form.label :content
    = form.text_area :content, required: true

  .actions
    = form.submit "Save Post"

app/views/posts/edit.html.slim
h1 Editing post

== render "form", post: @post

br

div
  => link_to "Show this post", @post
  '|
  =< link_to "Back to posts", root_path

app/views/posts/index.html.slim
div.p-5
  h1.mb-3 投稿一覧
  p style="color: green" = notice
  = link_to "新規追加", new_post_path, class: 'btn btn-outline-info btn-sm m-3'
  = link_to "スプレッドシートに出力", export_to_spreadsheet_posts_path, class: 'btn btn-outline-primary btn-sm'
  .d-flex.flex-wrap.align-items-center
    - @posts.each do |post|
      .card.border.m-3 style="width: 400px;"
        .card-header.h5 = post.title
        .card-body
          .float-right
            button.copy-button.btn.btn-outline-secondary.btn-sm data-target="post_#{post.id}"
              i.far.fa-copy.mr-1
              span.copy-text コピー
          div id="post_#{post.id}"
            .mb-3 = post.content
          = link_to "詳細", post, class: 'btn btn-outline-secondary btn-sm mr-1'
          = link_to "編集", edit_post_path(post), class: 'btn btn btn-outline-info btn-sm mr-1'
          = link_to "削除", post, method: :delete, data: { turbo: "true", turbo_method: :delete, turbo_confirm: '削除しますか?' }, class: "btn btn-outline-danger btn-sm"

app/views/posts/new.html.slim
h1 New post

== render "form", post: @post

br

div
  = link_to "Back to posts", root_path

app/views/posts/show.html.slim
p style="color: green" = notice

h1 = @post.title

p
  | 内容:
  = @post.content

div
  = link_to "Edit this post", edit_post_path(@post)
  | |
  = link_to "Back to posts", root_path

= button_to "Destroy this post", @post, method: :delete, data: { confirm: "Are you sure?" }